### ISSUE TITLE
Empty Hand Not Updating When Item Is Dropped

### ISSUE THREAD

**Issue by LoneWolffy** [randombyte-developer/entity-particles#4]
To reproduce, give yourself a particle attachment item/remover into an empty hand/hotbar slot.
After you have done this, use your drop item key (default Q) to drop it out of your inventory
Proceed to find an entity, and right click as if you use the item to apply a particle effect.

The particle will be added, however you can continue and do this for any other entity you wish ;

To remove this effect, place another item or block into the same slot in your hotbar and update the slot ; you will now regain your normal hand and can return to pick up the item

*Note* I have yet to be able to reproduce the bug under the circumstance that you shift click or remove the item in any way other than simply dropping it.

Sponge 3361
Forge 2705

**Comment by LoneWolffy** [comment]
This has been traced to a Sponge issue, now fixed in SF 3375 !
Sorry for the wasted issue

**Comment by randombyte-developer** [comment]
Specifically https://github.com/SpongePowered/SpongeCommon/commit/fd903ec7546b4629039023641d8ab31601372795 for future reference.
